In [4]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

In [5]:
# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 小数第3位まで表示
%precision 3

'%.3f'

In [6]:
data = np.array([7, 9, 2, 5, 10, 2, 4, 8])
data

array([ 7,  9,  2,  5, 10,  2,  4,  8])

In [10]:
random.seed(0)

# 正規分布
rnd_data = random.randn(10)
print('乱数10個の配列: ', rnd_data)

乱数10個の配列:  [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [13]:
# ランダム抽出
# 重複あり
print(random.choice(data, 5))

[2 4 8 8 7]


In [19]:
# 重複無し
# 重複無しなので、データ個数より大きい抽出はエラーとなる
print(random.choice(data, 5, False))

[ 2  2  8 10  9]
